spring:
    security:
        oauth2:
            client:
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response

                registration:
                    kakao:
                        client-id: # 채우기
                        client-secret: # 채우기
                        authorization-grant-type: authorization_code
                        client-authentication-method: client_secret_post
                        # oauth2 라이브러리에 고정되어 있는 redirect-uri (수정하지 말 것)
                        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                        client-name: kakao
                        scope:
#                            - account_email
                    naver:
                        client-id: # 채우기
                        client-secret: # 채우기
                        authorization-grant-type: authorization_code
                        client-authentication-method: client_secret_post
                        # oauth2 라이브러리에 고정되어 있는 redirect-uri (수정하지 말 것)
                        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                        client-name: naver
                        scope:
#                            - account_email

